### ISSUE TITLE
.jar file is not available

### ISSUE THREAD

**Issue by srinimech1** [locked-fg/osmosis-srtm-plugin#13]
Below website is not working anymore. I couldnot find/get the .jar file.
https://dl.bintray.com/locked-fg/Osmosis-Srtm-Plugin/

Could you please provide me the .jar file?

Many thanks,

**Comment by locked-fg** [comment]
Hey there, 
oups. I just recompiled/packaged the source, can you please try & verify this?
Just unpack the zip, then you should have the JAR file.
[srtmplugin-1.1.2.jar.zip](https://github.com/locked-fg/osmosis-srtm-plugin/files/8027597/srtmplugin-1.1.2.jar.zip)
When you've verified it, I'll look for a new home for the JAR.

Thanks a lot

**Comment by srinimech1** [comment]
Hallo Mr.Franz Graf,

Many thanks for very quick reply and JAR file. It is working and i get output .osm file with tag height data.
But getting an error as below while running the command in Windows CMD.

I have followed below procedure.
  1) Install osmosis-0.48.3 version
  2) Put srtmplugin-1.1.2.jar file in /lib/default (because /bin/plugins not working)
  3) Create osmosis-plugins.conf file in /config with line ,de.locked.osmosis.srtmplugin.SrtmPlugin_loader'
  4) Running command as below, which succussfuly creates output file with Height tag but also giving an error as below

C:\Tools\osmosis-0.48.3\bin>osmosis.bat --read-xml C:\Daten\Sandbox\A6\Elevation\SRTM\koeln.osm --write-srtm locDir=C:\Daten\Sandbox\A6\Elevation\SRTM\SrtmCache_Osmosis locOnly=true --write-xml C:\Daten\Sandbox\A6\Elevation\SRTM\koeln_srtm_newJar.osm
Feb 09, 2022 10:57:36 AM org.openstreetmap.osmosis.core.Osmosis run
INFORMATION: Osmosis Version 0.48.3
Feb 09, 2022 10:57:36 AM org.openstreetmap.osmosis.core.Osmosis run
INFORMATION: Preparing pipeline.
Feb 09, 2022 10:57:36 AM org.openstreetmap.osmosis.core.Osmosis run
INFORMATION: Launching pipeline execution.
Feb 09, 2022 10:57:36 AM org.openstreetmap.osmosis.core.Osmosis run
INFORMATION: Pipeline executing, waiting for completion.
Feb 09, 2022 10:57:38 AM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
Severe: Thread for task 1-read-xml failed
java.lang.AbstractMethodError: de.locked.osmosis.srtmplugin.SrtmPlugin_task.close()V
        at org.openstreetmap.osmosis.xml.v0_6.XmlReader.run(XmlReader.java:55)
        at java.lang.Thread.run(Unknown Source)

Feb 09, 2022 10:57:38 AM org.openstreetmap.osmosis.core.Osmosis main
Severe: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:47)


Many thanks & Regards,
Srini

**Comment by locked-fg** [comment]
Hey Srini,
hu? okay. so it's ALMOST good.
Would it be okay if you try it with an older osmosis-version? Because it names "Thread for task 1-read-xml failed" which is BEFORE this plugin. 
Thanks

**Comment by srinimech1** [comment]
Hello Mr.Franz Graf,

again many thanks for your valuable comment. 
With older version osmosis-0.45, it is running fine, generating expected output file and no errors.
Only with later version, i was getting an error. Would it be possible to rectify the error, which occur with later versions?

C:\Tools\osmosis-0.45\bin>osmosis.bat --read-xml C:\Daten\Sandbox\A6\Elevation\Braunschweig_srtm\chk.osm --write-srtm locDir=C:\Daten\Sandbox\A6\Elevation\Braunschweig_srtm\SrtmCache_Osmosis locOnly=true tagName=ele --write-xml C:\Daten\Sandbox\A6\Elevation\Braunschweig_srtm\chk_srtm.osm
Feb 11, 2022 7:35:52 PM org.openstreetmap.osmosis.core.Osmosis run
INFORMATION: Osmosis Version 0.45
Feb 11, 2022 7:35:52 PM org.openstreetmap.osmosis.core.Osmosis run
INFORMATION: Preparing pipeline.
Feb 11, 2022 7:35:52 PM org.openstreetmap.osmosis.core.Osmosis run
INFORMATION: Launching pipeline execution.
Feb 11, 2022 7:35:52 PM org.openstreetmap.osmosis.core.Osmosis run
INFORMATION: Pipeline executing, waiting for completion.
Feb 11, 2022 7:36:04 PM org.openstreetmap.osmosis.core.Osmosis run
INFORMATION: Pipeline complete.
Feb 11, 2022 7:36:04 PM org.openstreetmap.osmosis.core.Osmosis run
INFORMATION: Total execution time: 12672 milliseconds.

Thanks & Regards,
Srini

**Comment by locked-fg** [comment]
Hey Srini,
awesome. Thank you! I will first adjust the install instructions - but at least we now know that it is a version-issue from AFTER Osmosis 0.45. I don't know when / if I will have the time and motivation to dig into this. It requires reading through the Osmosis release notes and/or checking current examples and/or contacting the Osmosis devs .. If you're willing to help. You're welcome. But thank you already so far. I'll prepare a 1.1.2 release shortly.

**Comment by locked-fg** [comment]
And just realized that I already have the issue mentioned under known issues!
> Running the plugin in Osmosis 0.46 will throw error messages, but still provide the correct output.

But I'll adjust the install notes

**Comment by srinimech1** [comment]
Hey Franz,
yes..you are right. That's why i have tried 0.45.  Initially i read this note, but exact error message was not mentioned.
So only, i raised a query.
I could help regarding checking latest versions. But i am just a beginner with Python and Java.
So if you could guide me, i could definetely help/check, what i can do.

Regards,
Srini

**Comment by locked-fg** [comment]
Hey Srini,
phew good question. Maybe you could ask the Osmosis team what could have happened between 0.45 and later that produces such an error. The next possibility would be to check the Osmosis code/guide how a current plugin needs to be set up.
The errormessage "java.lang.AbstractMethodError: de.locked.osmosis.srtmplugin.SrtmPlugin_task.close()V" sounds like the problem is there somewhere. Maybe it just needs to be implemented.
